epsilon = 'epsilon'
estado_final_algoritmo_gramatica = 'Novo Estado Final'
simbolo_implicacao_gramatica = '->'
simbolo_ou_gramatica = '|'
sentenca_vazia = ''
status = 'status'
NAO_VISITADO = 'branco'
JA_VISITADO = 'preto'